---
homebrew_cask_packages:
  # general
  - name: 1password
  - name: dropbox
  - name: google-chrome
  - name: google-japanese-ime
  - name: macvim
  - name: messenger
  - name: skitch
  - name: slack
  - name: thunderbird
  - name: zoom

  # development
  - name: bruno
  - name: figma
  - name: orbstack
  - name: visual-studio-code

  # mobile development
  - name: android-studio
  - name: flipper
  - name: zulu@21

  # publishing
  - name: mactex

  # game
  - name: obs
