---
homebrew_cask_packages:
  # general
  - name: 1password
  - name: dropbox
  - name: google-chrome
  - name: google-japanese-ime
  - name: macvim
  - name: messenger
  - name: raycast
  - name: slack
  - name: thunderbird
  - name: zoom

  # development
  - name: bruno
  - name: docker
  - name: figma
  - name: visual-studio-code

  # mobile development
  - name: android-studio
  - name: flipper
  - name: zulu
