---
homebrew_packages:
  # general
  - name: coreutils
  - name: ffmpeg
  - name: imagemagick
  - name: tree
  - name: zsh-completions

  # development
  - name: awscli
  - name: git
  - name: gitmoji
  - name: jq
  - name: mise
  - name: neovim
  - name: watchman
  - name: hyperfine
  - name: xcodesorg/made/xcodes

  # management
  - name: gpg
  - name: pinentry-mac
